version: '3.8'

services:
  nginx-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: gradex-nginx-proxy:latest
    container_name: gradex_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge 